---
version: '3'
services:
  web:
    image: "amelia/php:7.2"
    volumes:
      - ".:/srv/code"
      - "./pki/certificate.pem:/etc/nginx/certs/certificate.pem:ro"
      - "./pki/privkey.pem:/etc/nginx/certs/privkey.pem:ro"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - redis

  app:
    image: "amelia/php:7.2"
    command: "php artisan horizon"
    volumes:
      - ".:/srv/code"
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - "redis-data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  db:
    image: "postgres:10-alpine"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: lolibrary
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "db-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d lolibrary -h localhost -U lolibrary -p 5432"]
      interval: 5s
      timeout: 8s
      retries: 3

  node:
    image: "node:9"
    command: ["sh", "-c", "npm rebuild node-sass --force && npm install && npm run watch"]
    working_dir: "/home/node"
    volumes:
      - ".:/home/node"
volumes:
  db-data:
  redis-data:
