---
version: '3'
services:
  www.lolibrary.test:
    image: "amelia/php:7.2"
    command:
      - "sh"
      - "-c"
      - |
        composer update
        php artisan wait:db
        php artisan wait:redis
        php artisan migrate --seed
        php artisan serve --host=0.0.0.0 --port=8080
    volumes:
      - "./app/frontend:/srv/code"
      - "./app/models:/srv/code/app/Models:ro"
      - "./app/database:/srv/code/database"
      - "./app/config:/srv/code/config:ro"
      - "./app/bootstrap:/srv/code/bootstrap"
      - "./.env:/secrets/environment/.env:ro"
    depends_on:
      - db.lolibrary.test
      - redis.lolibrary.test
      - minio.lolibrary.test
      - imaginary.lolibrary.test
    expose:
      - 8080

  app:
    restart: always
    image: "amelia/php:7.2"
    command:
      - "sh"
      - "-c"
      - |
        sleep 45
        php artisan wait:db
        php artisan wait:redis
        php artisan horizon
    volumes:
      - "./app/frontend:/srv/code"
      - "./app/models:/srv/code/app/Models:ro"
      - "./app/database:/srv/code/database"
      - "./app/config:/srv/code/config:ro"
      - "./app/bootstrap:/srv/code/bootstrap"
      - "./.env:/secrets/environment/.env:ro"
    depends_on:
      - db.lolibrary.test
      - redis.lolibrary.test
      - minio.lolibrary.test
      - imaginary.lolibrary.test
  
  api.lolibrary.test:
    image: "amelia/php:7.2"
    command:
      - "sh"
      - "-c"
      - |
        composer update
        php artisan wait:db
        php artisan wait:redis
        php -S 0.0.0.0:8080 /srv/code/server.php
    expose:
      - 8080
    volumes:
      - "./app/api:/srv/code"
      - "./app/models:/srv/code/app/Models:ro"
      - "./app/config:/srv/code/config:ro"
      - "./.env:/secrets/environment/.env:ro"
    depends_on:
      - db.lolibrary.test
      - redis.lolibrary.test
      - minio.lolibrary.test

  node:
    image: "node:10"
    command: ["sh", "-c", "npm install && npm run watch"]
    working_dir: "/home/node"
    volumes:
      - "./app/frontend:/home/node"

  imaginary.lolibrary.test:
    image: "h2non/imaginary:1"
    command: -enable-url-source
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
  
  minio.lolibrary.test:
    image: "minio/minio:latest"
    volumes:
      - "minio-data:/data"
    command: ["minio", "server", "/data"]
    environment:
      MINIO_ACCESS_KEY: MinioAccessKey
      MINIO_SECRET_KEY: SecretExampleKey
  
  db.lolibrary.test:
    image: "postgres:10-alpine"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: lolibrary
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "db-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d lolibrary -h localhost -U lolibrary -p 5432"]
      interval: 5s
      timeout: 8s
      retries: 3
    ports:
      - "5432:5432"
    
  redis.lolibrary.test:
    image: "redis:alpine"
    command: ["redis-server"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "6379:6379"
  
  proxy:
    build: ./app/proxy
    volumes:
      - "./app/proxy/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./pki/certificate.pem:/etc/nginx/certs/certificate.pem:ro"
      - "./pki/privkey.pem:/etc/nginx/certs/privkey.pem:ro"
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    depends_on:
      - www.lolibrary.test
      - api.lolibrary.test
      - minio.lolibrary.test
      - imaginary.lolibrary.test
volumes:
  db-data:
  minio-data:
