---
version: '3.4'
services:
  test:
    build:
      context: ./app
      dockerfile: ./frontend/Dockerfile
      target: build
    command:
      - "sh"
      - "-c"
      - |
        set -e
        php artisan wait:db
        php artisan wait:redis
        php artisan migrate:fresh --seed --force --no-interaction
        vendor/bin/phpunit
    depends_on:
      - db.lolibrary.test
      - redis.lolibrary.test

  db.lolibrary.test:
    image: "postgres:10-alpine"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: lolibrary
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d lolibrary -h localhost -U lolibrary -p 5432"]
      interval: 5s
      timeout: 8s
      retries: 3

  redis.lolibrary.test:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3
