---
version: '3'
services:
  web:
    image: "amelia/php:7.2"
    volumes:
      - ".:/srv/code"
      - "./pki/certificate.pem:/etc/nginx/certs/certificate.pem:ro"
      - "./pki/privkey.pem:/etc/nginx/certs/privkey.pem:ro"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      interval: 5s
      timeout: 15s
      retries: 2

  app:
    image: "amelia/php:7.2"
    command: "php artisan horizon"
    volumes:
      - ".:/srv/code"
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  db:
    image: "postgres:10-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: lolibrary
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "db-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5432"]
      interval: 5s
      timeout: 8s
      retries: 3

  node:
    image: "node:9"
    command: ["sh", "-c", "npm install && npm rebuild node-sass --force && npm run watch"]
    working_dir: "/home/node"
    volumes:
      - ".:/home/node"
volumes:
  db-data:
  redis-data: