---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: org.lolibrary.debug.psql
    lolibrary.org/routing-name: debug.psql
  name: debug-psql
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: org.lolibrary.debug.psql
      lolibrary.org/routing-name: debug.psql
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: org.lolibrary.debug.psql
        lolibrary.org/routing-name: debug.psql
    spec:
      containers:
        - image: "postgres:alpine"
          imagePullPolicy: IfNotPresent
          name: psql
          envFrom:
            - secretRef:
                name: php-cloud-sql
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 25m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 56Mi
        - command:
            - /cloud_sql_proxy
            - -instances=lolibrary-180111:us-central1:lolibrary=tcp:5432
            - -credential_file=/secrets/cloudsql/credentials.json
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          imagePullPolicy: IfNotPresent
          name: cloudsql-proxy
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - mountPath: /secrets/cloudsql
              name: cloudsql-instance-credentials
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            defaultMode: 420
            secretName: cloudsql-instance-credentials
