---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s-user
  namespace: lolibrary
  selfLink: /api/v1/namespaces/lolibrary/serviceaccounts/s-user
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    lolibrary.org/routing-name: service.user
  name: s-user
  namespace: lolibrary
  selfLink: /apis/extensions/v1beta1/namespaces/lolibrary/deployments/s-user
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: org.lolibrary.service.user
      lolibrary.org/routing-name: service.user
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: org.lolibrary.service.user
        lolibrary.org/routing-name: service.user
      namespace: lolibrary
    spec:
      serviceAccountName: s-user
      containers:
        - name: s-user
          securityContext:
            readOnlyRootFilesystem: true
          image: PLACEHOLDER
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "80"
            - name: REGION
              value: "us-central1"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: GOMAXPROCS
              value: "1"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: dsn
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 30m
              memory: 30Mi
          ports:
            - containerPort: 80
              name: http-service
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
              httpHeaders:
                - name: Host
                  value: service.user
          volumeMounts:
            - name: cockroach-service-account
              mountPath: /certs
              readOnly: true
      volumes:
        - name: cockroach-service-account
          secret:
            defaultMode: 0400
            secretName: cockroach-service-account
---
apiVersion: v1
kind: Service
metadata:
  labels:
    lolibrary.org/routing-name: service.user
  name: s-user
  namespace: lolibrary
  selfLink: /api/v1/namespaces/lolibrary/services/s-user
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: org.lolibrary.service.user
    lolibrary.org/routing-name: service.user
  sessionAffinity: None
  type: ClusterIP
