---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s-template
  namespace: lolibrary
  selfLink: /api/v1/namespaces/lolibrary/serviceaccounts/s-template
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    lolibrary.org/routing-name: template.service
  name: s-template
  namespace: lolibrary
  selfLink: /apis/extensions/v1beta1/namespaces/lolibrary/deployments/s-template
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: org.lolibrary.template.service
      lolibrary.org/routing-name: template.service
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: org.lolibrary.template.service
        lolibrary.org/routing-name: template.service
      namespace: lolibrary
    spec:
      serviceAccountName: s-template
      containers:
        - name: s-template
          securityContext:
            readOnlyRootFilesystem: true
          image: PLACEHOLDER
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "80"
            - name: REGION
              value: "us-central1"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: GOMAXPROCS
              value: "1"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: dsn
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/run/secrets/google/key.json"
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 30m
              memory: 30Mi
          ports:
            - containerPort: 80
              name: http-service
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
              httpHeaders:
                - name: Host
                  value: template.service
          volumeMounts:
            - name: pod-google-credentials
              mountPath: /var/run/secrets/google
              readOnly: true
            - name: ca-certs
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes:
        - name: pod-google-credentials
          secret:
            defaultMode: 0400
            secretName: pod-google-credentials
        - name: ca-certs
          secret:
            defaultMode: 0444
            secretName: ca-certs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    lolibrary.org/routing-name: template.service
  name: s-template
  namespace: lolibrary
  selfLink: /api/v1/namespaces/lolibrary/services/s-template
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: org.lolibrary.template.service
    lolibrary.org/routing-name: template.service
  sessionAffinity: None
  type: ClusterIP
