---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-backup-cockroachdb
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: running-kitten-cockroachdb
          initContainers:
            - name: init-certs
              image: cockroachdb/cockroach-k8s-request-cert:0.4
              imagePullPolicy: IfNotPresent
              command:
                - "/bin/ash"
                - "-ecx"
                - "/request-cert -namespace=${POD_NAMESPACE} -certs-dir=/cockroach-certs -type=client -user=root -symlink-ca-from=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              volumeMounts:
                - name: client-certs
                  mountPath: /cockroach-certs
          containers:
            - name: cockroachdb-client
              image: "gcr.io/lolibrary-180111/cron-backup-cockroachdb:2019-06-06.0"
              imagePullPolicy: IfNotPresent
              env:
                - name: COCKROACH_CERTS_DIR
                  value: /cockroach-certs
                - name: COCKROACH_HOST
                  value: running-kitten-cockroachdb-public
                - name: COCKROACH_USER
                  value: root
                - name: CRON_PING_URL
                  valueFrom:
                    secretKeyRef:
                      name: cron-backup-cockroachdb-ping
                      key: url
              volumeMounts:
                - name: client-certs
                  mountPath: /cockroach-certs
                - name: cockroach-backup-sa
                  mountPath: /var/run/secrets/google
                  readOnly: true
              command:
                - /usr/bin/backup
                - lolibrary
                - "gs://lolibrary-cockroachdb-backups"
                - cockroachdb-backup-sa
                - "$CRON_PING_URL"
          volumes:
            - name: client-certs
              emptyDir: {}
            - name: cockroach-backup-sa
              secret:
                defaultMode: 0400
                secretName: cockroach-backup-sa
