---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-proxy-api
  namespace: default
  selfLink: /api/v1/namespaces/default/serviceaccounts/edge-proxy-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    lolibrary.org/routing-name: edge-proxy.api
  name: edge-proxy-api
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/edge-proxy-api
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: org.lolibrary.edge-proxy.api
      lolibrary.org/routing-name: edge-proxy.api
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: org.lolibrary.edge-proxy.api
        lolibrary.org/routing-name: edge-proxy.api
      namespace: default
    spec:
      serviceAccountName: edge-proxy-api
      containers:
        - name: edge-proxy-api
          securityContext:
            readOnlyRootFilesystem: true
          image: PLACEHOLDER
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "80"
            - name: REGION
              value: "us-central1"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: GOMAXPROCS
              value: "1"
          resources:
            requests:
              cpu: 25m
              memory: 25Mi
            limits:
              cpu: 50m
              memory: 50Mi
          ports:
            - containerPort: 80
              name: http-service
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: 80
              httpHeaders:
                - name: Host
                  value: edge-proxy.api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    lolibrary.org/routing-name: edge-proxy.api
  name: edge-proxy-api
  namespace: default
  selfLink: /api/v1/namespaces/default/services/edge-proxy-api
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: org.lolibrary.edge-proxy.api
    lolibrary.org/routing-name: edge-proxy.api
  sessionAffinity: None
  type: NodePort
