---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  labels:
    app: currency
    svc: typhon
spec:
  replicas: 3
  limits:

  containers:
    - name: currency
        image: lolibrary/microservice-currency:latest
        ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: currency
spec:
  type: NodePort
  selector:
    app: currency
    svc: typhon
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000